apply plugin: 'com.android.application'

android {
    namespace "com.google.android.youtube.pro"  
    compileSdk 36

    defaultConfig {
        applicationId "com.google.android.youtube.pro"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 1
        versionName "4.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    // Add your dependencies here
    implementation 'androidx.webkit:webkit:1.12.0'
}



